local ShopConfig = {
	-- ==================== KNIVES ====================
	["Karambit"] = {
		Category = "Knives",
		Rarity = "Legendary",
		Price = 500,
		Description = "uhhh a karambit or something lol idk :P",
		ImageId = "rbxassetid://0",
		ModelName = "Karambit",
		LayoutOrder = 1,
	},

	["Butterfly Knife"] = {
		Category = "Knives",
		Rarity = "Epic",
		Price = 350,
		Description = "oh it so cool wowow",
		ImageId = "rbxassetid://0",
		ModelName = "ButterflyKnife",
		LayoutOrder = 2,
	},
}

return ShopConfig
