return {
	Murderer = {
		Name = "MURDERER",
		Description = "Eliminate everyone without getting caught",
		Icon = "rbxassetid://94253718781024",
		MainColor = Color3.fromHex("F14541"),
		DiamondOutsideBorder = "rbxassetid://108604173753578",
		DiamondInsideBorder = "rbxassetid://103690070687718",
	},

	Sheriff = {
		Name = "SHERIFF",
		Description = "Eliminate the murderer without dying",
		Icon = "rbxassetid://101142949537395",
		MainColor = Color3.fromHex("417FF1"),
		DiamondOutsideBorder = "rbxassetid://99945706437855",
		DiamondInsideBorder = "rbxassetid://131683707152683",
	},

	Innocent = {
		Name = "INNOCENT",
		Description = "Hide & Survive",
		Icon = "rbxassetid://79779765741463",
		MainColor = Color3.fromHex("00F836"),
		DiamondOutsideBorder = "rbxassetid://94159005580506",
		DiamondInsideBorder = "rbxassetid://81394674004616",
	},
}
