local ItemConfig = {
	-- ==================== KNIVES ====================
	["DefaultKnife"] = {
		Category = "Knives",
		Rarity = "Common",
		Creator = "Creator - jayfullsends",
		Description = "just a knife lol :d",
		ModelName = "DefaultKnife",
		ImageId = "rbxassetid://0",
	},

	["Karambit"] = {
		Category = "Knives",
		Rarity = "Legendary",
		Creator = "Creator - jayfullsends",
		Description = "uhhh a karambit or something lol idk :P",
		ModelName = "Karambit",
		ImageId = "rbxassetid://133301072618931",
	},

	["Butterfly"] = {
		Category = "Knives",
		Rarity = "Epic",
		Creator = "Creator - jayfullsends",
		Description = "oh it so cool wowow",
		ModelName = "ButterflyKnife",
		ImageId = "rbxassetid://0",
	},

	["ShadowBlade"] = {
		Category = "Knives",
		Rarity = "Legendary",
		Creator = "Creator - jayfullsends",
		Description = "just a knife lol :p",
		ModelName = "ShadowBlade",
		ImageId = "rbxassetid://0",
	},

	["GoldenKnife"] = {
		Category = "Knives",
		Rarity = "Epic",
		Creator = "Creator - jayfullsends",
		Description = "just a knife lol :p",
		ModelName = "GoldenKnife",
		ImageId = "rbxassetid://0",
	},

	["TrustBlade"] = {
		Category = "Knives",
		Rarity = "Mythic",
		Creator = "Creator - jayfullsends",
		Description = "just a knife lol :p",
		ModelName = "TrustBlade",
		ImageId = "rbxassetid://0",
	},

	-- ==================== Guns ====================
	["DefaultRevolver"] = {
		Category = "Guns",
		Rarity = "Common",
		Creator = "Creator - jayfullsends",
		Description = "just a gun lol",
		ModelName = "DefaultRevolver",
		ImageId = "rbxassetid://0",
	},
}

return ItemConfig
